export const partyMock = {
  id: 6,
  name: 'Хэллоуинская Ночь',
  type: 'ROCK',
  city: 'Минск',
  statusOfParticipationRequest: '',
  organizerUsername: 'mihail123fd',
  ageRestriction: 18,
  guests: [
    {
      id: 3,
      age: 18,
      username: 'some',
      rating: 3.0,
    },
  ],
  countOfPlaces: 50,
  description:
    'Тематика вечера — хоррор, с костюмированным конкурсом и призами.',
  coordinates: '54.953,27.618',
  minimalRating: 0,
  ticketCost: 55,
  dateOfEvent: '2025-11-01T22:00:00',
};

export const guestsRequestsMock = {
  totalElements: 10,
  content: [
    {
      id: 1,
      age: 18,
      username: 'Same',
      rate: 3,
    },
    {
      id: 2,
      age: 18,
      username: 'Same2',
      rate: 2,
    },
    {
      id: 3,
      age: 18,
      username: 'Same3',
      rate: 3,
    },
    {
      id: 4,
      age: 18,
      username: 'Same4',
      rate: 5,
    },
  ],
}

export const listOfPartiesMock = {
  totalElements: 10,
  content: [
    {
      id: 6,
      name: 'Хэллоуинская Ночь',
      type: 'ROCK',
      organizerUsername: 'mihail123fd',
      ageRestriction: 18,
      guests: [],
      countOfPlaces: 50,
      description:
        'Тематика вечера — хоррор, с костюмированным конкурсом и призами.',
      coordinates: '54.953,27.618',
      minimalRating: 0,
      ticketCost: 55,
      dateOfEvent: '2025-11-01T22:00:00',
    },
    {
      id: 8,
      name: 'Ретро-Вечеринка',
      type: 'ROCK',
      organizerUsername: 'mihail123fd',
      ageRestriction: 18,
      guests: [],
      countOfPlaces: 100,
      description:
        'Летний вечер в стиле 80-х с живой музыкой и танцами до утра.',
      coordinates: '54.953,27.618',
      minimalRating: 0,
      ticketCost: 60,
      dateOfEvent: '2025-08-15T20:00:00',
    },
  ],
};

export const organizatorslistOfPartiesMock = {
  totalElements: 10,
  content: [
    {
      id: 1,
      name: 'Хэллоуинская Ночь',
      type: 'ROCK',
      ageRestriction: 18,
      organizerUsername: 'mihail123fd',
      countOfPlaces: 50,
      ticketCost: 55,
      status: 'UNAVAILABLE',
      dateOfEvent: '2025-11-01T22:00:00',
    },
    {
      id: 2,
      name: 'Хэллоуинская Ночь',
      type: 'ROCK',
      ageRestriction: 18,
      organizerUsername: 'mihail123fd',
      countOfPlaces: 50,
      ticketCost: 55,
      status: 'WAIT_FOR_DELETING',
      dateOfEvent: '2025-11-01T22:00:00',
    },
    {
      id: 3,
      name: 'Хэллоуинская Ночь',
      type: 'ROCK',
      ageRestriction: 18,
      organizerUsername: 'mihail123fd',
      countOfPlaces: 50,
      ticketCost: 55,
      status: 'WAIT_FOR_UPDATING',
      dateOfEvent: '2025-11-01T22:00:00',
    },
    {
      id: 4,
      name: 'Хэллоуинская Ночь',
      type: 'ROCK',
      ageRestriction: 18,
      organizerUsername: 'mihail123fd',
      countOfPlaces: 50,
      ticketCost: 55,
      status: 'WAIT_FOR_CREATING',
      dateOfEvent: '2025-11-01T22:00:00',
    },
    {
      id: 5,
      name: 'Ретро-Вечеринка',
      type: 'ROCK',
      ageRestriction: 18,
      countOfPlaces: 100,
      organizerUsername: 'mihail123fd',
      ticketCost: 60,
      status: 'PENDING_REVISION',
      dateOfEvent: '2025-08-15T20:00:00',
    },
    {
      id: 6,
      name: 'Ретро-Вечеринка',
      type: 'ROCK',
      ageRestriction: 18,
      countOfPlaces: 100,
      organizerUsername: 'mihail123fd',
      ticketCost: 60,
      status: 'REJECTED_FOR_UPDATE',
      dateOfEvent: '2025-08-15T20:00:00',
    },
  ],
};

export const userslistOfPartiesMock = {
  totalElements: 10,
  content: [
    {
      id: 6,
      name: 'Хэллоуинская Ночь',
      type: 'ROCK',
      ageRestriction: 18,
      countOfPlaces: 50,
      organizerUsername: 'mihail123fd',
      ticketCost: 55,
      status: 'ACCEPTED',
      dateOfEvent: '2025-11-01T22:00:00',
    },
    {
      id: 8,
      name: 'Ретро-Вечеринка',
      type: 'ROCK',
      ageRestriction: 18,
      countOfPlaces: 100,
      organizerUsername: 'mihail123fd',
      ticketCost: 60,
      status: 'REJECTED',
      dateOfEvent: '2025-08-15T20:00:00',
    },
    {
      id: 9,
      name: 'Ретро-Вечеринка',
      type: 'ROCK',
      ageRestriction: 18,
      countOfPlaces: 100,
      organizerUsername: 'mihail123fd',
      ticketCost: 60,
      status: 'IN_PROCESS',
      dateOfEvent: '2025-08-15T20:00:00',
    },
  ],
};
export const adminslistOfPartiesMock = {
  totalElements: 10,
  content: [
    {
      id: 1,
      name: 'Хэллоуинская Ночь',
      type: 'ROCK',
      ageRestriction: 18,
      organizerUsername: 'mihail123fd',
      countOfPlaces: 50,
      ticketCost: 55,
      status: 'UNAVAILABLE',
      dateOfEvent: '2025-11-01T22:00:00',
    },
    {
      id: 2,
      name: 'Хэллоуинская Ночь',
      type: 'ROCK',
      ageRestriction: 18,
      organizerUsername: 'mihail123fd',
      countOfPlaces: 50,
      ticketCost: 55,
      status: 'WAIT_FOR_DELETING',
      dateOfEvent: '2025-11-01T22:00:00',
    },
    {
      id: 3,
      name: 'Хэллоуинская Ночь',
      type: 'ROCK',
      ageRestriction: 18,
      organizerUsername: 'mihail123fd',
      countOfPlaces: 50,
      ticketCost: 55,
      status: 'WAIT_FOR_UPDATING',
      dateOfEvent: '2025-11-01T22:00:00',
    },
    {
      id: 4,
      name: 'Хэллоуинская Ночь',
      type: 'ROCK',
      ageRestriction: 18,
      organizerUsername: 'mihail123fd',
      countOfPlaces: 50,
      ticketCost: 55,
      status: 'WAIT_FOR_CREATING',
      dateOfEvent: '2025-11-01T22:00:00',
    },
    {
      id: 5,
      name: 'Ретро-Вечеринка',
      type: 'ROCK',
      ageRestriction: 18,
      countOfPlaces: 100,
      organizerUsername: 'mihail123fd',
      ticketCost: 60,
      status: 'PENDING_REVISION',
      dateOfEvent: '2025-08-15T20:00:00',
    },
    {
      id: 6,
      name: 'Ретро-Вечеринка',
      type: 'ROCK',
      ageRestriction: 18,
      countOfPlaces: 100,
      organizerUsername: 'mihail123fd',
      ticketCost: 60,
      status: 'REJECTED_FOR_UPDATE',
      dateOfEvent: '2025-08-15T20:00:00',
    },
  ],
};

export const partyTypes = [
  {
    id: 1,
    name: 'TECHO',
  },
  {
    id: 2,
    name: 'ROCK',
  },
];
